"""empty message

Revision ID: 8fad0c5f2b7f
Revises: 94576aaecd47
Create Date: 2024-07-18 01:57:52.421077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fad0c5f2b7f'
down_revision: Union[str, None] = '94576aaecd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_column('favorites', 'user_id')
    # ### end Alembic commands ###
